### ISSUE TITLE
Übersetzungsfehler in Quotes

### ISSUE THREAD

**Issue by descry12** [prudolf/vTigerLanguage#1]
Quotes.php - Zeile 23

aktuelle Übersetzung:  'Open Quotes' => 'Offene Zitate',
bessere Übersetzung:   'Open Quotes' => 'Offene Angebote',

Open Quotes wird meines Wissens in vtiger lediglich im Rahmen eines vorgefertigten Filters Namens "Open Quotes" verwendet. Dieser Filter zeigt eben jene Angebote an, deren "Quote Stage" ungleich accepted oder rejected ist. Das heißt, es handelt sich hier um Angebote zu welchen noch kein Ergebnis vorliegt. Ich halte "offene Angebote" als Übersetzungsvorschalg insofern für durchaus treffend.

**Comment by prudolf** [comment]
Danke habs geändert-... Hast natürlich recht :-)
